/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,ts,jsx,tsx}", "./components/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#5c647a",
        primary: "#004ac6",
        "on-primary": "#ffffff",
        "surface-container-low": "#f3f3f3",
        "on-primary-fixed": "#00174b",
        "inverse-primary": "#b4c5ff",
        "surface-border": "#E2E8F0",
        "surface-container-highest": "#e2e2e2",
        "primary-fixed-dim": "#b4c5ff",
        "on-tertiary-fixed": "#161c22",
        "primary-fixed": "#dbe1ff",
        "on-primary-container": "#eeefff",
        "surface-bright": "#f9f9f9",
        "text-primary": "#0F172A",
        "error-red": "#DC2626",
        "on-tertiary": "#ffffff",
        "surface-container": "#eeeeee",
        "on-secondary-fixed": "#131b2e",
        "primary-container": "#2563eb",
        surface: "#f9f9f9",
        "on-background": "#1a1c1c",
        "secondary-container": "#dae2fd",
        "tertiary-container": "#676e75",
        "on-secondary": "#ffffff",
        "surface-tint": "#0053db",
        "outline-variant": "#c3c6d7",
        "on-primary-fixed-variant": "#003ea8",
        "tertiary-fixed-dim": "#c1c7cf",
        "inverse-surface": "#2f3131",
        secondary: "#565e74",
        "on-surface": "#1a1c1c",
        "on-secondary-fixed-variant": "#3f465c",
        "on-surface-variant": "#434655",
        outline: "#737686",
        "surface-container-lowest": "#ffffff",
        background: "#f9f9f9",
        "on-error-container": "#93000a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "surface-variant": "#e2e2e2",
        tertiary: "#4f565c",
        error: "#ba1a1a",
        "tertiary-fixed": "#dde3eb",
        "salary-green": "#059669",
        "inverse-on-surface": "#f0f1f1",
        "on-tertiary-fixed-variant": "#41474e",
        "secondary-fixed-dim": "#bec6e0",
        "text-secondary": "#475569",
        "surface-dim": "#dadada",
        "surface-container-high": "#e8e8e8",
        "on-tertiary-container": "#ebf1f9",
        "secondary-fixed": "#dae2fd"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        "stack-sm": "8px",
        "stack-lg": "24px",
        "margin-mobile": "16px",
        "container-max": "1280px",
        gutter: "24px",
        "margin-desktop": "32px",
        "stack-md": "16px",
        "section-padding": "64px"
      },
      maxWidth: {
        "container-max": "1280px"
      },
      fontFamily: {
        "label-sm": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "display-lg-mobile": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "label-sm": ["12px", { lineHeight: "14px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-lg": ["30px", { lineHeight: "38px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "label-md": ["14px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "500" }]
      }
    }
  },
  plugins: []
};
